# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: NzFiYTFmZmRiN2MzOGZiZjg1ZWM0YzgwYmZhY2I2MWEyMDBhOWYxODJhMDhhYTFiNzZkNGMwZDZlNWJlZjQyZjI5YWRiYzg3N2U1MzhlOTVmMzQ0NmMyNzdhOTViZmZiYTlhNzRkYmYxZmY4NmM0ZGUwYzQwYTc2YWJkZTlhYTM=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@localhost:8761/eureka/
